id: P006676
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD107152
  title: དབུ་མ་རྒྱན་རྩ་འགྲེལ
  author: ''
  volumes:
    f6e1b38cc0d64c279bcf6434644dc843:
      image_group_id: I1PD107154
      title: ''
      volume_number: 1
      total_pages: 466
      base_file: v001.txt
